apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: server-1
  region: eu-central-1

nodeGroups:
  - name: backend-jack
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 10
    

cloudWatch:
    clusterLogging:
        enableTypes: ["*"]

